Print result

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -21,6 +21,8 @@ jobs:
       - name: Run Specs
         run: |
           /snap/bin/godot-4 --headless -s spec/gspec_test.gd
+          echo "$?"
           if [ "$?" != '0' ]; then
+            echo "this failed..."
             exit "$?"
           fi
